
        ##########################################################
        ## Pushbullet - Notification Test
        ##########################################################
  - alias: Pushbullet Text Test
    trigger:
      platform: state
      entity_id: input_boolean.test_text_notification
      from: 'off'
      to: 'on'
    condition:
      condition: state
      entity_id: device_tracker.life360_trevor
      state: 'home'
    action:
      - service: notify.pushbullet
        data:
          title: "Home Assistant"
          message: "This is a test."
      - service: homeassistant.turn_off
        entity_id: input_boolean.test_text_notification