homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret homeassistant_timezone
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages


####################################################
#                                                  #
#                     Enables                      #
#                                                  #
####################################################
config:
recorder:
updater:
discovery:
conversation:
history:
logbook:
map:
sun:
custom_updater:
  track:
    - cards
    - components
    - python_scripts
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
  component_urls:
    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/custom_components.json
  python_script_urls:
    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/python_scripts.json

hue:
  bridges:
    - host: !secret hue_ip

################################################################
#  Cloud   https://www.nabucasa.com/config/google_assistant/   #
################################################################
#cloud:
#  google_actions:
#    filter:
#      include_entities:
#        - light.piano_lamp
#        - light.small_lamp
#        - light.bedroom
#        - switch.wemo_switch
#        - media_player.living_room
#        - media_player.dining_room
####      include_domains:
####        - switch
####      exclude_entities:
####        - switch.outside
#    entity_config:
#      light.bedroom:
#        name: Bedroom Light
#        aliases:
#         - Trevor's Bedside
#        room: bedroom
#      switch.wemo_switch:
#        name: Wemo Switch
#        aliases:
#         - wemo
#         - wemo light
#         - wemo lamp
#        room: living room
#      media_player.dining_room:
#        name: Dining Room Sonos
#        aliases:
#         - Dining Sonos
#         - play 1
#         - Dining Room Sonos
#        room: dining room

####################################################
#                                                  #
#               MQTT                               #
####################################################
mqtt:
  broker: '192.168.2.34' #127.0.0.1
  port: 1883 #1883
  client_id: 'hassio-terminal-client'
  username: 'pi'
  password: 'HsdfyYr78'
#  birth_message:
#    topic: 'hass/status'
#    payload: 'online'
#    qos: 1
#    retain: true
#  will_message:
#    topic: 'hass/status'
#    payload: 'offline'
#    qos: 1
#    retain: true

####################################################
#                                                  #
#        Themes and UI config                      #
#                                                  #
####################################################
frontend:
  javascript_version: latest
  themes:
    alert_yellow:
      primary-text-color: '#FFC000'
      paper-item-icon-color: '#FFC000'
    alert_red:
      primary-text-color: '#FF0000'
      paper-item-icon-color: '#FF0000'


http:
  api_password: !secret http_api_password
  login_attempts_threshold: 2
  trusted_networks:
    - 127.0.0.1
   # - 192.168.2.1/34
    #- !secret external_ip
    - !secret external_ip

##############################
#    Binary Sensors          #
##############################

#binary_sensor:
#see package info_sensors for : iss, 

##############################
#    Sensors                 #
##############################

sensor:
# see package info_sensors for: fitbit, pocketcasts, alphavantage
# see package things_status for: 
####### Security
  - platform: authenticated

light:
#  - platform: mqtt
#    name: 'Office RGB light'
#    state_topic: 'office/rgb1/light/status'
#    command_topic: 'office/rgb1/light/switch'
#    brightness_state_topic: 'office/rgb1/brightness/status'
#    brightness_command_topic: 'office/rgb1/brightness/set'
#    rgb_state_topic: 'office/rgb1/rgb/status'
#    rgb_command_topic: 'office/rgb1/rgb/set'
#    brightness_scale: 100
#    retain: true
#    optimistic: false
#    qos: 0
  - platform: mqtt
    name: 'office_light1'
    state_topic: 'office/light1/status'
    command_topic: 'office/light1/switch'
    optimistic: false

switch:
  platform: mqtt
  name: 'Office Switch'
  state_topic: 'office/switch1/status'
  command_topic: 'office/switch1/set'
  retain: true
  optimistic: false

#device_tracker:
#for nmap and ping see things_status package
#                 for life360 see info_sensor package

##############################################
#            Components                      #
##############################################

# Text to speech
tts:
  - platform: google

tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: !secret tuya_country_code

duckdns:
  domain: 261
  access_token: !secret duckdns_access_token

camera:
  - platform: mjpeg
    mjpeg_url: http://192.168.2.24:8081
    name: FamilyRoomPi Camera

#android_ip_webcam:
#  - host: 192.168.2.37
#    port: 8080
#    sensors:
#      - audio_connections
#      - battery_level
#      - battery_temp
#      - battery_voltage
#      - light
#      - motion
#      - pressure
#      - proximity
#      - sound
#      - video_connections
#    switches:
#      - exposure_lock
#      - ffc
#      - focus
#      - gps_active
#      - night_vision
#      - overlay
#      - torch
#      - whitebalance_lock
#      - video_recording

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://192.168.2.34:3218
  ssh:
    title: SSH
    icon: mdi:wrench
    url: http://192.168.2.34:7681/
#  nodered:
#    title: nodered
#    icon: mdi:wrench
#    url: http://192.168.2.34:1880
  pihole:
    title: Pi-hole
    icon: mdi:block-helper
    url: http://192.168.2.34:4865/admin/index.php
  mqtt:
    title: MQTT
    icon: mdi:code-brackets
    url: http://192.168.2.34:5713
  motioneye:
    title: motionEye
    icon: mdi:cctv
    url: http://192.168.2.34:8765


#################################################
#         Includes                              #
#################################################

zone: !include zones.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
#shell_command: !include shell_commands.yaml
input_number: !include input_number.yaml
input_boolean: !include input_boolean.yaml

