###########################################################
#                                                         #
# This file runs a check of my configuration before it is #
# merged in to the master branch on Github to ensure that #
# the code in the repo is fully valid                     #
#                                                         #
###########################################################


version: 2
jobs:
  build:
    docker:
      - image: homeassistant/amd64-homeassistant
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Check config
          command: |
            mv travis_secrets.yaml secrets.yaml
            hass -c homeassistant/ --script check_config --info all
