###############################################################################
#   @author         :   Haleefacts
#   @date           :   24/02/2018
#   @package        :   
#   @description    :   
#   @url            :   
###############################################################################
homeassistant:
  customize:
    device_tracker.life360_trevor:
      friendly_name: Trevor
    device_tracker.life360_corynne:
      friendly_name: Corynne
      
group:

input_number:

input_select:

sensor:

  - platform: mqtt
    name: 'Latitude'
    state_topic: "trevor/S8/gps/longitude"
  - platform: mqtt
    state_topic: "owntracks/pi/trevors phone"
    name: "Battery S8"
    unit_of_measurement: "%"
    value_template: '{{ value_json.batt }}'
    device_class: battery

#  - platform: history_stats
#    name: stats_work
#    entity_id: device_tracker.trevor........
#    state: 'Work'
#    type: time
#    end: '{{ now() }}'
#    duration:
#      days: 7

device_tracker:
  - platform: life360
    username: !secret life360_username
    password: !secret life360_password
    prefix: life360
    show_as_state: driving, moving, places
    driving_speed: 18
    max_gps_accuracy: 200
    max_update_wait:
      minutes: 30
    members:
      - Trevor
      - Corynne

###############################################################################
#                               Automations
###############################################################################
automation: