###############################################################################
#   @author         :   Haleefacts
#   @date           :   24/02/2018
#   @package        :   
#   @description    :   
#   @url            :   
###############################################################################
homeassistant:
  customize:

group:

input_number:

input_select:

sensor:

automation:
        ###############################
        #  Backup
        ###############################
  - alias: Daily Backup at 3 AM
    trigger:
      platform: time
      at: '3:00:00'
    action:
      - service: hassio.snapshot_full
        data_template:
          name: Automated Backup {{ now().strftime('%Y-%m-%d') }}
      - service: notify.pushbullet
        data:
          title: "Home Assistant"
          message: "Daily snapshot taken."
## Upload snapshot to Dropbox
  - alias: Upload dropbox 4 AM
    trigger:
      platform: time
      at: '4:00:00'
    action:
    - service: hassio.addon_stdin
      data_template:
        addon: 7be23ff5_dropbox_sync
        input: {"command":"upload"}