###############################################################################
#   @author         :   HalEEfacts
#   @date           :   01/11/2018
#   @package        :   Theme Control
#   @description    :   
#   @url            :   
###############################################################################
frontend:
  themes:
    darkblue:
      primary-color: "#396FB6"
      light-primary-color: "#77a0d4"
      dark-primary-color: "#3539ce"
      text-primary-color: "#ffffff"
      primary-background-color: "#37464f"
      sidebar-text_-_background: "#3c4348"
      paper-card-background-color: "#263137"
      paper-card-header-color: "var(--text-primary-color)"
      secondary-background-color: "var(--primary-background-color)"
      primary-text-color: "var(--text-primary-color)"
      secondary-text-color: "var(--primary-color)"
      paper-listbox-background-color: "var(--sidebar-text_-_background)"
      paper-toggle-button-checked-ink-color: "var(--dark-primary-color)"
      paper-toggle-button-checked-button-color: "var(--dark-primary-color)"
      paper-toggle-button-checked-bar-color: "var(--dark-primary-color)"
      paper-slider-knob-color: "var(--primary-color)"
      paper-slider-knob-start-color: "var(--primary-color)"
      paper-slider-pin-color: "var(--primary-color)"
      paper-slider-active-color: "var(--primary-color)"
      paper-slider-secondary-color: "var(--light-primary-color)"
      paper-slider-container-color: "var(--sidebar-text_-_background)"
      paper-progress-secondary-color: "var(--sidebar-text_-_background)"
      paper-item-selected_-_background-color: "var(--primary-color)"
      paper-item-icon_-_color: "var(--text-primary-color)"
      paper-item-icon-color: "var(--text-primary-color)"
      paper-item-icon-active-color: "var(--primary-color)"
      paper-grey-50: "var(--sidebar-text_-_background)"
      paper-grey-200: "var(--primary-background-color)"
      label-badge-background-color: "var(--sidebar-text_-_background)"
      label-badge-text-color: "var(--text-primary-color)"
      label-badge-red: "var(--primary-color)"
      label-badge-blue: "var(--light-primary-color)"
      label-badge-green: "var(--dark-primary-color)"
      label-badge-yellow: "var(--text-primary-color)"
      label-badge-grey: "var(--paper-grey-500)"
      table-row-background-color: "var(--paper-card-background-color)"
      table-row-alternative-background-color: "var(--sidebar-text_-_background)"
    
    test1:
      primary-color: "#030814"
      paper-tabs-selection-bar-color: "#ff0051"
      light-primary-color: "#00355f"
      dark-primary-color: "#2e4faa"
      text-primary-color: "#999999"
      primary-background-color: "#424242"
      sidebar-text_-_background: "#303030"
      paper-card-background-color: "#2d2d2d"
      paper-card-header-color: "#111111"
      secondary-background-color: "var(--primary-background-color)"
      primary-text-color: "#999999"
      secondary-text-color: "#6d6d6d"
      paper-listbox-background-color: "var(--sidebar-text_-_background)"
      paper-toggle-button-checked-ink-color: "var(--dark-primary-color)"
      paper-toggle-button-checked-button-color: "var(--dark-primary-color)"
      paper-toggle-button-checked-bar-color: "var(--dark-primary-color)"
      paper-slider-knob-color: "#2e4faa"
      paper-slider-knob-start-color: "#424242"
      paper-slider-pin-color: "#194587"
      paper-slider-pin-start-color: "var(--dark-primary-color)"
      paper-slider-active-color: "#1b2f66"
      paper-slider-secondary-color: "#111111"   
      paper-slider-container-color: "#111111" 
      paper-progress-secondary-color: "var(--sidebar-text_-_background)"
      paper-item-selected_-_background-color: "#77a0d4"
      paper-item-icon_-_color: "#396FB6"
      paper-item-icon-color: "#999999"
#      paper-item-icon-active-color: "#999999"
      paper-grey-50: "var(--sidebar-text_-_background)"
      paper-grey-200: "var(--primary-background-color)"
      label-badge-background-color: "var(--sidebar-text_-_background)"
      label-badge-text-color: "var(--text-primary-color)"
      label-badge-red: "#396FB6"
      label-badge-blue: "var(--light-primary-color)"
      label-badge-green: "var(--dark-primary-color)"
      label-badge-yellow: "var(--text-primary-color)"
      label-badge-grey: "var(--paper-grey-500)"
      table-row-background-color: "var(--paper-card-background-color)"
      table-row-alternative-background-color: "var(--sidebar-text_-_background)"
      paper-font-headline_-_letter-spacing: '-0.5px'
      paper-font-headline_-_font-weight: '450'
      paper-font-headline_-_font-size: '20px'
###############################################################################
#                               Automations
###############################################################################
automation:
  - alias: 'Set Day theme at startup'
    initial_state: 'on'
    trigger:
    - platform: homeassistant
      event: start
    condition:
      condition: sun
      after: sunrise
      after_offset: '+00:30:00'
    action:
    - service: frontend.set_theme
      data:
        name: default
#  - alias: 'Set Night theme at startup'
#    initial_state: 'on'
#    trigger:
#    - platform: homeassistant
#      event: start
#    condition:
#      condition: sun
#      after: sunset
#    action:
#    - service: frontend.set_theme
#      data:
#        name: darkblue
  - alias: Set Night Mode Theme after Sunset
    trigger:
    - platform: sun
      event: sunset
      offset: '-01:00:00'
    action:
    - service: frontend.set_theme
      data:
        name: darkblue  